#!/bin/bash
#!/bin/bash
#----------------------------------------------------------------------------------------------------
function getPathGrep() {
	local PATH_GREP=$(dirname $1)
	if [ "$PATH_GREP" == "." ]
	then
		PATH_GREP=$PATH_IDENT
	else
		PATH_GREP=$PATH_IDENT/${PATH_GREP:2}
	fi
	
	echo $PATH_GREP
}
#----------------------------------------------------------------------------------------------------
function get_window_id() {
	local WINDOW_ID=""
	for n in $*
	do
		local FILENAME=$(basename $n)" ("
		local PATH_GREP=$(getPathGrep $n)
		WINDOW_ID=$(wmctrl -l | grep "$PATH_GREP"| grep "gedit" | grep "$FILENAME" | cut -f1 -d" ")
		if [ "$WINDOW_ID" != "" ]
		then
			break
		fi
	done
	
    echo $WINDOW_ID
}
#----------------------------------------------------------------------------------------------------
function get_workspace()	{
	local  N=$(wmctrl -d | cut -d' ' -f8 | cut -d',' -f1)
	echo $N
}

#----------------------------------------------------------------------------------------------------
function wait_id()	{
	local ID=""
	while [ "$ID" == "" ]
	do
		ID=$(get_window_id $*)
	done
}
#----------------------------------------------------------------------------------------------------
function isOpen()	{
	for i in $*
	do
		local FILE_GREP=$(basename $i)" ("
		local PATH_GREP=$(getPathGrep $i)

		local OUVERT=$(wmctrl -l | grep "$PATH_GREP" | grep "gedit" | grep "$FILE_GREP" )
		if [ "$OUVERT" != "" ]
		then
			echo $OUVERT
			return
		fi
	done
	echo ""
}
#----------------------------------------------------------------------------------------------------
function open()	{
	
	local OPEN=$(isOpen $*)
	if [ "$OPEN" == "" ]
	then
		echo "  Creation de la fenetre d'edition" ... $SIZE
		edition $* &>/dev/null
		wait_id $*
		wmctrl -i -r $(get_window_id $*) -e $SIZE
		#echo "  "wmctrl -i -r $(get_window_id $*) -e $SIZE
		return
	fi
	echo $(isOpen $*)
}
#----------------------------------------------------------------------------------------------------
#											MAIN
#----------------------------------------------------------------------------------------------------
STR0="./src/lib/*.cpp"
STR1="./src/lib/*.h"
STR2="ed makefile src/depend.py src/build_makefile src/build_include src/makefile.base"
#-----------------------------------------
PATH_IDENT="programmes/opengl/lib-wmcgl"
#----------------------------------------------------------------------------------------------------
OFFSET="-0"
[ "$(uname -n)" == "poste-portable" ] && OFFSET="50"

SCREEN_SIZE=$(xdpyinfo  | grep dimensions | sed "s/.*dimensions: *\(.*x.*\) pixels.*/\1/g")
SCREEN_WIDTH=$(echo $SCREEN_SIZE | sed "s/\(.*\)x.*/\1/g")
SCREEN_HEIGHT=$(echo $SCREEN_SIZE | sed "s/.*x\(.*\)/\1/g")

SCREEN_WIDTH=$(( $SCREEN_WIDTH / 2 ))
WIDTH=$(( $SCREEN_WIDTH / 2 + 200))
WIDTH=1100
HEIGHT=$(( $SCREEN_HEIGHT - $OFFSET )) 

echo "------------------------------------------------------------"
echo "  total        SCREEN       calculé"
echo $SCREEN_SIZE"     "$SCREEN_WIDTH"x"$SCREEN_HEIGHT"     "$WIDTH"x"$HEIGHT
echo ------------------------------------------------------------
#exit
#----------------------------------------------------------------------------------------------------
POSX=0
POSY=0
case "$(hostname)" in
	"poste-002")
		POSX=-72
		POSY=-14

		WIDTH=1140
		HEIGHT=1249
		;;
esac

SIZE="0,$POSX,$POSY,$WIDTH,$HEIGHT"
echo "Fenetre STR0 "$SIZE
open $STR0

#----------------------------------------------------------------------------------------------------
POSX=$(( $POSX + 100 ))
case "$(hostname)" in
	"poste-002")
		POSX=818
		POSY=-14
		;;
esac

SIZE="0,$POSX,$POSY,$WIDTH,$HEIGHT"
echo "Fenetre STR1 "$SIZE
open $STR1

#----------------------------------------------------------------------------------------------------
case "$(hostname)" in
	"poste-002")
		POSX=$(($SCREEN_WIDTH-36))
		POSY=-64
		;;
esac

SIZE="0,$POSX,$POSY,$WIDTH,$HEIGHT"
echo "Fenetre STR2 "$SIZE
open $STR2
#----------------------------------------------------------------------------------------------------

